### ISSUE TITLE
Create a "favorites" app

### ISSUE THREAD

**Issue by stenington** [stenington/django-sandbox#1]
Create a new app in this project named `favorites` with a model called `Favorite` that has a text field named `name`. Set it up so you can create `Favorite`s through the admin.

**Comment by rachwyatt** [comment]
Oops, I just pushed straight to master. This part seems pretty straightforward even though I always have to google to remember what commands I'm looking for on a lot of things. I guess the more I do it, I won't have to look it up anymore. I need a cheat sheet.
