### ISSUE TITLE
Add form for creating favorites

### ISSUE THREAD

**Issue by stenington** [stenington/django-sandbox#4]
~~Add a form to the main page that accepts text and creates new favorites.~~

**Comment by stenington** [comment]
@rachwyatt This is the next ticket to attempt, but actually let's amend it a bit. First, create a new page at `/new` that lets you fill out a form to add an item to the list of favorites. The index page should have a link that says "Add to list" which takes me to that page, and when I submit that form successfully, it should take me back to the index. Make sense?

**Comment by rachwyatt** [comment]
makes sense, thanks!
